export enum MESSAGE_TYPES {
  USER_CONNECTED = 'USER_CONNECTED',
  USER_DISCONNECTED = 'USER_DISCONNECTED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  USER_TYPING = 'USER_TYPING',
  USER_STOPPED_TYPING = 'USER_STOPPED_TYPING',
}

export type Message = {
  type: MESSAGE_TYPES,
  data: object,
};